name: Run API Tests

on:
  push:
    branches:
      - main

jobs:
  api_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Postman Tests
        uses: dannydainton/gh-action-postman@v2
        with:
          collection: tests/postman_collection.json
          environment: tests/postman_environment.json
