name: API Testing CI/CD Pipeline

on:
  push:
    branches:
      - main  # Виконання тестів при пуші на основну гілку
  pull_request:
    branches:
      - main  # Запуск тестів при pull request на основну гілку

jobs:
  api-tests:
    runs-on: ubuntu-latest  # Використовуємо Ubuntu для CI/CD

    steps:
      # Крок 1: Checkout коду з репозиторію
      - name: Checkout code
        uses: actions/checkout@v2

      # Крок 2: Налаштування Python середовища
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ось, наприклад, Python 3.9

      # Крок 3: Встановлення залежностей з requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Крок 4: Встановлення Node.js (версія 16 або новіша)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Встановлюємо Node.js версії 16

      # Крок 5: Встановлення Newman
      - name: Install Newman
        run: |
          npm install -g newman  # Встановлюємо Newman глобально

      # Крок 6: Запуск API тестів через Newman (Postman CLI)
      - name: Run Postman API Tests
        run: |
          newman --version  # Логування версії Newman для перевірки
          newman run bakery.postman_collection.json --environment bakery.postman_environment.json --reporters junit --reporter-junit-export results.xml

      # Крок 7: Публікація результатів тестування
      - name: Publish test results
        if: always()  # Цей крок виконується навіть у разі помилки тестів
        run: |
          # Публікуємо або записуємо лог у ваш CI/CD систему
          # Можна використовувати lcov, junit, або інші формати для звітів
          cat results.xml
